# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import HTMLTestRunner
import sys
import HTMLTestRunner
import time
import os

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://templates.jinshuju.net/detail/Dv9JPD")
    self.driver.set_window_size(1366, 728)

    self.driver.find_element(By.CSS_SELECTOR, ".choice-wrapper:nth-child(2) .ant-radio-input").click()
    # 调用截屏方法
    self.driver.get_screenshot_as_file('../image/image1.png')
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn").click()




   # self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-affix-wrapper-focused > .ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-picker-cell-today > .ant-picker-cell-inner").click()
    self.driver.find_element(By.ID, "TextInputfield_19").click()
    self.driver.find_element(By.ID, "TextInputfield_19").send_keys("自动化")
    self.driver.find_element(By.NAME, "field_20").click()
    self.driver.find_element(By.NAME, "field_20").send_keys("1388888888")

    self.driver.get_screenshot_as_file('../image/image2.png')
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(2)").click()
    element = self.driver.find_element(By.NAME, "field_20")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.NAME, "field_20")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.NAME, "field_20")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "field_20").click()
    self.driver.find_element(By.NAME, "field_20").send_keys("13888888888")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "TextInputfield_23").click()
    self.driver.find_element(By.ID, "TextInputfield_23").send_keys("测试公司")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-focused .ant-input-number-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-focused .ant-input-number-input").send_keys("99")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-affix-wrapper-focused > .ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-picker-cell-today > .ant-picker-cell-inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-focused .ant-input-number-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-focused .ant-input-number-input").send_keys("0")
    self.driver.find_element(By.ID, "TextInputfield_27").click()
    self.driver.find_element(By.ID, "TextInputfield_27").send_keys("赵冬燕")
    self.driver.find_element(By.NAME, "field_28").click()
    self.driver.find_element(By.NAME, "field_28").send_keys("13888888888")
    self.driver.find_element(By.NAME, "field_29").click()
    self.driver.find_element(By.NAME, "field_29").send_keys("测试内容")
    self.driver.get_screenshot_as_file('../image/image3.png')
    self.driver.find_element(By.CSS_SELECTOR, ".published-form__submit").click()

    self.driver.get_screenshot_as_file('../image/image4.png')

    assert text ==( '企业复工申请资料提交表 提交成功', '断言成功')

    self.driver.find_element(By.CSS_SELECTOR, ".gd-icon-check-circle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".main-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message").click()


cur_time = time.strftime('%Y-%m-%d_%H_%M_%S')
filename = os.path.dirname(os.path.abspath('.')) + '\\report\\' + cur_time + '.html'
f = open(filename, "wb")
runner = HTMLTestRunner.HTMLTestRunner(stream=f, title="测试报告", description='测试报告描述')

