name: CI
on: [push, pull_request]
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [21]
        operating-system: [ubuntu-latest]
        distribution: [ 'temurin' ]
    steps:
      - name: Prepare
        uses: actions/checkout@v4
      - name: Set Up Java Development Kit
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
      - name: Maven build clean, build, test and install
        run: |
          mvn clean install -Dmaven.test.skip=true
          mvn test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ success() }}
        with:
          files: "**/target/surefire-reports/*.xml"
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage to Codecov
        if: ${{ success() }}
        uses: codecov/codecov-action@v5
        with:
          files: "target/site/jacoco/jacoco.xml"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: SonarCloud Scan
        if: ${{ success() }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          entryPoint: 'sonar-scanner'
          args: >
            -Dsonar.projectKey=alaahong_open_automation_quiz
            -Dsonar.organization=alaahong
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}