name: CI
on: [push, pull_request]
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [17]
        operating-system: [ubuntu-latest]
    steps:
      - name: Prepare
        uses: actions/checkout@v1
      - name: Set Up Java Development Kit
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Maven build clean, build, test and install
        run: |
          mvn clean install -Dmaven.test.skip=true
          mvn test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: "**/target/surefire-reports/*.xml"
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: "target/site/jacoco/jacoco.xml"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}