name: CI Copilot Failure Prompt

on:
  workflow_run:
    # IMPORTANT: list the workflows you want to monitor for completion
    # Replace the example names below with your actual workflow names.
    workflows:
      - CI
      - Build
      - Test
    types: [completed]
permissions:
  actions: read
  contents: read
  pull-requests: write
  issues: write

jobs:
  prompt:
    if: >
      github.event.workflow_job.conclusion != 'success' &&
      github.event.workflow_job.workflow_name != 'CI Copilot Failure Prompt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Post PR/Issue comment with Copilot-ready prompt (links only)
        env:
          # gh CLI 使用 GH_TOKEN；同时保留 GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_job.run_id }}
          JOB_ID: ${{ github.event.workflow_job.id }}
          JOB_NAME: ${{ github.event.workflow_job.name }}
          WORKFLOW_NAME: ${{ github.event.workflow_job.workflow_name }}
          REPO: ${{ github.repository }}
          API_URL: ${{ github.api_url }}
          SERVER_URL: ${{ github.server_url }}
        run: |
          java scripts/CiCopilotPrompt.java