name: CI Copilot Failure Prompt

on:
  workflow_run:
    # IMPORTANT: list the workflows you want to monitor for completion
    # Replace the example names below with your actual workflow names.
    workflows:
      - CI
      - Build
      - Test
    types: [completed]

permissions:
  actions: read
  contents: read
  pull-requests: write
  issues: write

jobs:
  prompt:
    if: >
      github.event.workflow_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download logs for failed run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p logs
          curl -sSL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/logs" \
            -o logs.zip || true

          if [ -f logs.zip ]; then
            unzip -q logs.zip -d logs || true
          fi

          # 合并每个 step 的末尾日志，限制体量
          find logs -type f -name "*.txt" -print0 | xargs -0 -I{} sh -c 'echo -e "\n==== {} ====\n"; tail -n 2000 "{}"' > logs/combined.txt || true

          if [ ! -s logs/combined.txt ]; then
            echo "No step logs were available to download for run ${{ github.event.workflow_run.id }}." > logs/combined.txt
          fi

      - name: Post PR/Issue comment with Copilot-ready prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO: ${{ github.repository }}
          JOB_NAME: all
          WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
          API_URL: ${{ github.api_url }}
          SERVER_URL: ${{ github.server_url }}
        run: node scripts/ci_copilot_prompt.mjs