name: Nightly Build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  nightly-test:
    name: Nightly Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Test
        run: |
          mvn clean install -Dmaven.test.skip=true
          mvn test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco/jacoco.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

